/**
 * ข้อมูลสินค้าเสื้อผ้าเด็กและสินค้าทดสอบ 18 รายการ (Baby & Kids Clothing Products Data)
 * โหลดไฟล์จริงจากโฟลเดอร์ assets/images/product-1.jpg ถึง product-17.jpg ครบ 100%
 */

const PRODUCTS = [
  {
    id: 99,
    name: "เทสระบบชำระเงิน",
    nameEn: "Payment System Test (1 THB)",
    category: "test",
    categoryName: "ทดสอบระบบ",
    price: 1,
    originalPrice: 10,
    rating: 5.0,
    reviews: 999,
    tag: "เทสโอนเงิน 1 บาท",
    tagType: "hot",
    image: "assets/images/product-test.svg",
    imageCdn: "assets/images/product-test.svg",
    description: "สินค้าพิเศษสำหรับทดสอบระบบชำระเงินและทดสอบสแกน QR Code พร้อมเพย์จริง ยอดโอน 1.00 บาท โอนเข้าบัญชี 093-758-6699 พร้อมส่งหลักฐานสลิปและบันทึกออเดอร์ (ระบบฟรีค่าจัดส่ง 0 บาท เพื่อให้ออเดอร์นี้มียอดสุทธิ 1 บาทพอดี)",
    sizes: ["1 รายการ (฿1)"],
    colors: [
      { name: "QR พร้อมเพย์", code: "#ff2a85" },
      { name: "ทดสอบระบบ", code: "#00e5ff" }
    ],
    inStock: true,
    isTest: true,
    features: ["ราคา 1 บาท สำหรับทดสอบสแกนจ่ายจริง", "ยอดเงิน 1.00 บาท โอนเข้า 093-758-6699", "ฟรีค่าจัดส่ง 0 บาท"]
  },
  {
    id: 1,
    name: "ชุดหมีรอมเปอร์ลายน้องหมีสีพาสเทล",
    nameEn: "Pastel Teddy Bear Cotton Romper",
    category: "romper",
    categoryName: "ชุดรอมเปอร์",
    price: 350,
    originalPrice: 490,
    rating: 4.9,
    reviews: 142,
    tag: "ขายดีอันดับ 1",
    tagType: "hot",
    image: "assets/images/product-1.jpg",
    imageCdn: "assets/images/product-1.jpg",
    description: "ชุดหมีรอมเปอร์ตัดเย็บจากผ้าคอตตอนออร์แกนิก 100% สัมผัสนุ่มละมุนเป็นพิเศษ ไม่ระคายเคืองต่อผิวบอบบางของทารก ปักลายหน้าน้องหมีน่ารัก งานปักประณีตไร้รอยคันด้านใน มีกระดุมแป๊กด้านหน้าและเป้า สะดวกต่อการเปลี่ยนผ้าอ้อม",
    sizes: ["0-3M", "3-6M", "6-12M", "1-2Y"],
    colors: [
      { name: "เบจครีม", code: "#e8d8c8" },
      { name: "ชมพูซอฟต์", code: "#fce7f3" },
      { name: "ขาวงาช้าง", code: "#fcfaf2" }
    ],
    inStock: true,
    features: ["ผ้าคอตตอนออร์แกนิก 100%", "กระดุม Snap สะดวก", "ระบายอากาศดีเยี่ยม"]
  },
  {
    id: 2,
    name: "ชุดบอดี้สูทเด็กอ่อนผ้าร่องมินิมอล",
    nameEn: "Minimalist Ribbed Baby Bodysuit",
    category: "bodysuit",
    categoryName: "ชุดบอดี้สูท",
    price: 290,
    originalPrice: 390,
    rating: 4.8,
    reviews: 98,
    tag: "ยอดนิยม",
    tagType: "popular",
    image: "assets/images/product-2.jpg",
    imageCdn: "assets/images/product-2.jpg",
    description: "บอดี้สูทผ้าร่องเกรดพรีเมียม เนื้อผ้ายืดหยุ่นสูง ระบายอากาศได้ดีเยี่ยม เหมาะกับสภาพอากาศเมืองไทย สวมใส่สบาย กระชับคล่องตัว มาพร้อมหมวกบีนนี่เข้าชุดสีชมพูพาสเทล",
    sizes: ["0-3M", "3-6M", "6-12M"],
    colors: [
      { name: "ชมพูพาสเทล", code: "#ffb3c6" },
      { name: "ครีมละมุน", code: "#fdf0ed" },
      { name: "มอคค่าอ่อน", code: "#d8c4b6" }
    ],
    inStock: true,
    features: ["ผ้าร่องยืดหยุ่นสูง", "พร้อมหมวกบีนนี่", "ซักเครื่องได้ทรงไม่เสีย"]
  },
  {
    id: 3,
    name: "ชุดเซ็ตเสื้อกางเกงลินินเอิร์ธโทน",
    nameEn: "Earth Tone Natural Linen 2-Piece Set",
    category: "sets",
    categoryName: "ชุดเซ็ต",
    price: 420,
    originalPrice: 550,
    rating: 4.9,
    reviews: 86,
    tag: "มาใหม่",
    tagType: "new",
    image: "assets/images/product-3.jpg",
    imageCdn: "assets/images/product-3.jpg",
    description: "เซ็ตเสื้อคอจีนกระดุมกะลาพร้อมกางเกงขาสั้นขอบยางยืด ผลิตจากผ้าฝ้ายผสมลินินธรรมชาติ นุ่มเบา ไม่ร้อน ดีไซน์สไตล์มินิมอลญี่ปุ่น สวมใส่ได้ทั้งเด็กชายและเด็กหญิง",
    sizes: ["6-12M", "1-2Y", "2-3Y", "3-4Y"],
    colors: [
      { name: "เขียวเซจ", code: "#c1cfc0" },
      { name: "ชมพูพีช", code: "#ffd5cd" },
      { name: "ทรายธรรมชาติ", code: "#e4d5b7" }
    ],
    inStock: true,
    features: ["ผ้าลินินผสมคอตตอน", "ยางยืดนุ่มไม่รัดพุง", "สไตล์มินิมอลเจแปน"]
  },
  {
    id: 4,
    name: "ชุดเดรสเจ้าหญิงตัวน้อยผ้าทูลล์หวาน",
    nameEn: "Sweet Princess Tulle Baby Dress",
    category: "dress",
    categoryName: "ชุดเดรส",
    price: 490,
    originalPrice: 690,
    rating: 5.0,
    reviews: 215,
    tag: "แนะนำพิเศษ",
    tagType: "highlight",
    image: "assets/images/product-4.jpg",
    imageCdn: "assets/images/product-4.jpg",
    description: "เดรสเจ้าหญิงสีชมพูหวานละมุน ตัดเย็บซับในด้วยผ้าคอตตอนเนื้อนุ่ม 100% ซ้อนทับด้วยผ้าทูลล์เนื้อละเอียดฟรุ้งฟริ้ง ประดับลูกไม้คอบัวและโบว์ซาติน สวยหรูเหมาะสำหรับงานเลี้ยง ถ่ายรูป 1st Birthday",
    sizes: ["3-6M", "6-12M", "1-2Y", "2-3Y"],
    colors: [
      { name: "ชมพูเจ้าหญิง", code: "#ff8fab" },
      { name: "ขาวบริสุทธิ์", code: "#ffffff" }
    ],
    inStock: true,
    features: ["ซับในคอตตอน 100% กันคัน", "ผ้าทูลล์นุ่มพิเศษ", "เหมาะกับงานเฉลิมฉลอง"]
  },
  {
    id: 5,
    name: "ชุดเอี๊ยมยีนส์ขาสั้นสไตล์วินเทจ",
    nameEn: "Vintage Cute Denim Dungarees Set",
    category: "dungarees",
    categoryName: "ชุดเอี๊ยม",
    price: 390,
    originalPrice: 520,
    rating: 4.8,
    reviews: 110,
    tag: "ขายดี",
    tagType: "popular",
    image: "assets/images/product-5.jpg",
    imageCdn: "assets/images/product-5.jpg",
    description: "ชุดเอี๊ยมยีนส์ฟอกนิ่มขาสั้น ไม่แข็งกระด้าง ปรับระดับสายเอี๊ยมได้ 2 ระดับ พร้อมกระเป๋าหน้าใบเล็กน่ารัก แมตช์คู่กับเสื้อยืดลายทางคอกลม สไตล์เรโทรเท่ๆ",
    sizes: ["6-12M", "1-2Y", "2-3Y", "3-4Y"],
    colors: [
      { name: "ยีนส์ฟอกฟ้า", code: "#7ca1cc" },
      { name: "ยีนส์เข้มคลาสสิก", code: "#3a506b" }
    ],
    inStock: true,
    features: ["ผ้ายีนส์ฟอกนิ่มพิเศษ", "สายปรับระดับได้", "แถมเสื้อลายทาง"]
  },
  {
    id: 6,
    name: "ชุดนอนเด็กผ้าคอตตอนลายพิมพ์แสนนุ่ม",
    nameEn: "Cozy Floral Organic Cotton Pajamas",
    category: "sleepwear",
    categoryName: "ชุดนอน",
    price: 320,
    originalPrice: 450,
    rating: 4.9,
    reviews: 132,
    tag: "ผ้านุ่มพิเศษ",
    tagType: "popular",
    image: "assets/images/product-6.jpg",
    imageCdn: "assets/images/product-6.jpg",
    description: "ชุดนอนผ้าคอตตอนทอพิเศษ นุ่มสบาย ช่วยให้อุณหภูมิร่างกายคงที่ตลอดทั้งคืน ลายพิมพ์ดอกไม้สีชมพูอ่อน ขอบผ้านุ่ม ไม่รัดแน่นเวลาลูกนอนดิ้น",
    sizes: ["6-12M", "1-2Y", "2-3Y", "3-5Y"],
    colors: [
      { name: "ชมพูพิมพ์ลาย", code: "#ffb3c6" },
      { name: "ขาวคอตตอน", code: "#fcfaf2" }
    ],
    inStock: true,
    features: ["ผ้าคอตตอน 100% หายใจได้", "เนื้อผ้านุ่มละมุน", "ดีไซน์คิ้วท์"]
  },
  {
    id: 7,
    name: "เสื้อสเวตเตอร์ไหมพรมถักมือสำหรับเด็กอ่อน",
    nameEn: "Handknit Soft Baby Cardigan Sweater",
    category: "knitwear",
    categoryName: "เสื้อหนาว/ไหมพรม",
    price: 450,
    originalPrice: 590,
    rating: 5.0,
    reviews: 77,
    tag: "Handmade",
    tagType: "highlight",
    image: "assets/images/product-7.jpg",
    imageCdn: "assets/images/product-7.jpg",
    description: "สเวตเตอร์ไหมพรมเส้นใยนุ่มพิเศษ ไม่ระคายเคืองผิวเด็ก งานถักประณีต อบอุ่นกำลังดี เหมาะสำหรับใส่เดินทางท่องเที่ยวหรือในห้องปรับอากาศ",
    sizes: ["6-12M", "1-2Y", "2-3Y"],
    colors: [
      { name: "ชมพูพาสเทล", code: "#ff8fab" },
      { name: "ครีมวนิลา", code: "#eed7c5" }
    ],
    inStock: true,
    features: ["ไหมพรมเกรดเด็กอ่อน", "กระดุมด้านหน้าสวมง่าย", "นุ่มอุ่นไม่หนัก"]
  },
  {
    id: 8,
    name: "ชุดรอมเปอร์ผ้าฝ้ายคลาสสิกสบายตัว",
    nameEn: "Classic Cotton Baby Romper Suit",
    category: "romper",
    categoryName: "ชุดรอมเปอร์",
    price: 380,
    originalPrice: 480,
    rating: 4.7,
    reviews: 64,
    tag: "ผ้านุ่มสบาย",
    tagType: "new",
    image: "assets/images/product-8.jpg",
    imageCdn: "assets/images/product-8.jpg",
    description: "ชุดรอมเปอร์ผ้าฝ้ายทรงคลาสสิก ระบายเหงื่อได้ดีเยี่ยม แห้งไว ขอบขากระชับพอดี ช่วยให้น้องคลานและเคลื่อนไหวได้อย่างคล่องตัว",
    sizes: ["6-12M", "1-2Y", "2-3Y"],
    colors: [
      { name: "ฟ้าครามอ่อน", code: "#bde0fe" },
      { name: "ชมพูพาสเทล", code: "#ffcbf2" }
    ],
    inStock: true,
    features: ["ผ้าฝ้ายธรรมชาติ 100%", "ทรงหลวมใส่สบาย", "แห้งไวไม่อับชื้น"]
  },
  {
    id: 9,
    name: "ชุดเดรสเด็กอ่อนผ้าฝ้ายธรรมชาติระบายอากาศ",
    nameEn: "Breathable Gauze Cotton Baby Dress",
    category: "dress",
    categoryName: "ชุดเดรส",
    price: 340,
    originalPrice: 450,
    rating: 4.9,
    reviews: 105,
    tag: "ยอดนิยม",
    tagType: "popular",
    image: "assets/images/product-9.jpg",
    imageCdn: "assets/images/product-9.jpg",
    description: "ชุดเดรสเด็กอ่อนทำจากผ้าฝ้ายเนื้อโปร่ง 2 ชั้น นุ่มสบาย ยิ่งซักยิ่งนุ่ม สวมใส่ง่าย ระบายเหงื่อได้ยอดเยี่ยม เหมาะกับน้องแรกเกิดถึง 1 ขวบ",
    sizes: ["0-3M", "3-6M", "6-12M"],
    colors: [
      { name: "ขาวบริสุทธิ์", code: "#ffffff" },
      { name: "ชมพูอ่อน", code: "#ffb3c6" }
    ],
    inStock: true,
    features: ["ผ้าฝ้าย 100%", "ยิ่งซักยิ่งนุ่ม", "อ่อนโยนต่อผิวบอบบาง"]
  },
  {
    id: 10,
    name: "ชุดเอี๊ยมลายสก็อตน่ารักสไตล์เกาหลี",
    nameEn: "Korean Plaid Baby Overalls Set",
    category: "dungarees",
    categoryName: "ชุดเอี๊ยม",
    price: 490,
    originalPrice: 650,
    rating: 4.8,
    reviews: 58,
    tag: "แฟชั่นเกาหลี",
    tagType: "hot",
    image: "assets/images/product-10.jpg",
    imageCdn: "assets/images/product-10.jpg",
    description: "ชุดเอี๊ยมลายสก็อตสุดเท่ ตัดเย็บด้วยผ้านุ่มไม่บาดผิว สไตล์สตรีทแฟชั่นเกาหลี ทรงสวย คล่องตัว มาพร้อมกระดุมปรับระดับสาย",
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    colors: [
      { name: "สก็อตเทา-ชมพู", code: "#d8b4e2" },
      { name: "สก็อตคลาสสิก", code: "#b8c0cc" }
    ],
    inStock: true,
    features: ["สไตล์เกาหลีสุดฮิต", "สายปรับระดับได้", "ผ้านุ่มสบาย"]
  },
  {
    id: 11,
    name: "ชุดบอดี้สูทเด็กอ่อนผ้ายืดเนื้อนุ่มพิเศษ",
    nameEn: "Soft Stretch Infant Bodysuit",
    category: "bodysuit",
    categoryName: "ชุดบอดี้สูท",
    price: 310,
    originalPrice: 420,
    rating: 4.9,
    reviews: 89,
    tag: "สวมใส่ง่าย",
    tagType: "popular",
    image: "assets/images/product-11.jpg",
    imageCdn: "assets/images/product-11.jpg",
    description: "ชุดบอดี้สูทเนื้อผ้ายืดหยุ่นสูง โอบกระชับลำตัวลูกน้อยอย่างอ่อนโยน กระดุมเป้าแบบแป๊กเปลี่ยนผ้าอ้อมสะดวก สีชมพูพาสเทลละมุนตา",
    sizes: ["0-3M", "3-6M", "6-12M"],
    colors: [
      { name: "ชมพูซอฟต์", code: "#ffb3c6" },
      { name: "ฟ้าพาสเทล", code: "#bde0fe" }
    ],
    inStock: true,
    features: ["ผ้ายืดหยุ่นสูง", "กระดุมเป้าสะดวก", "ไม่ระคายเคือง"]
  },
  {
    id: 12,
    name: "ชุดเสื้อยืดเด็กผ้าคอตตอนพร้อมหมวกถัก",
    nameEn: "Baby Cotton Tee with Knitted Bonnet Set",
    category: "sets",
    categoryName: "ชุดเซ็ต",
    price: 380,
    originalPrice: 490,
    rating: 4.9,
    reviews: 147,
    tag: "ยอดนิยม",
    tagType: "popular",
    image: "assets/images/product-12.jpg",
    imageCdn: "assets/images/product-12.jpg",
    description: "เสื้อยืดเด็กผ้าคอตตอนเนื้อเนียนนุ่ม สกรีนลายน้องหมี แมตช์คู่กับหมวกบีนนี่ถักนุ่มนิ่ม โทนสีขาวตัดชมพู ถ่ายรูปน่ารักทุกมุม",
    sizes: ["3-6M", "6-12M", "1-2Y"],
    colors: [
      { name: "ขาว-ชมพู", code: "#ffb3c6" },
      { name: "ขาวงาช้าง", code: "#ffffff" }
    ],
    inStock: true,
    features: ["ผ้าคอตตอนเกรด A", "พร้อมหมวกบีนนี่", "แมตช์ง่ายน่ารัก"]
  },
  {
    id: 13,
    name: "ชุดบอดี้สูทสกรีนกราฟิก Hello World ผ้านุ่ม",
    nameEn: "Hello World Graphic Baby Bodysuit",
    category: "bodysuit",
    categoryName: "ชุดบอดี้สูท",
    price: 260,
    originalPrice: 350,
    rating: 4.8,
    reviews: 173,
    tag: "โปรโมชัน",
    tagType: "sale",
    image: "assets/images/product-13.jpg",
    imageCdn: "assets/images/product-13.jpg",
    description: "บอดี้สูทแขนสั้นสกรีนข้อความน่ารัก สีพิมพ์ปลอดสารพิษ (Non-toxic) ไม่ระคายเคืองแม้เข้าปาก คอเสื้อแบบ Envelope ขยายง่าย ไม่ติดศีรษะเวลาสวม",
    sizes: ["0-3M", "3-6M", "6-12M", "1-2Y"],
    colors: [
      { name: "ขาวออฟไวท์", code: "#f8f9fa" },
      { name: "ชมพูนม", code: "#ffcbf2" }
    ],
    inStock: true,
    features: ["สีสกรีน Non-toxic", "คอ Envelope ใส่ง่าย", "ผ้าคอตตอน 100%"]
  },
  {
    id: 14,
    name: "เสื้อคลุมแจ็คเก็ตไหมพรมกระดุมคู่สไตล์ยุโรป",
    nameEn: "Double-Button Knit Baby Jacket",
    category: "knitwear",
    categoryName: "เสื้อหนาว/ไหมพรม",
    price: 460,
    originalPrice: 620,
    rating: 4.9,
    reviews: 95,
    tag: "พรีเมียม",
    tagType: "highlight",
    image: "assets/images/product-14.jpg",
    imageCdn: "assets/images/product-14.jpg",
    description: "เสื้อคลุมแจ็คเก็ตไหมพรมถักลายละเอียด กระดุมหน้าคู่ โทนสีชมพูอ่อนหวาน สไตล์วินเทจยุโรป ให้ความอบอุ่นกำลังดี นุ่มสบายไม่คัน",
    sizes: ["3-6M", "6-12M", "1-2Y", "2-3Y"],
    colors: [
      { name: "ชมพูดัสตี้อ่อน", code: "#f2b5d4" },
      { name: "เบจโอ๊ตมีล", code: "#d9c5b2" }
    ],
    inStock: true,
    features: ["ไหมถักพรีเมียม", "สไตล์วินเทจยุโรป", "ไม่ย้วยหลังซัก"]
  },
  {
    id: 15,
    name: "ชุดเดรสเจ้าหญิงผ้าลูกไม้ไอริชหวานละมุน",
    nameEn: "Irish Lace Delicacy Baby Dress",
    category: "dress",
    categoryName: "ชุดเดรส",
    price: 550,
    originalPrice: 790,
    rating: 5.0,
    reviews: 188,
    tag: "แนะนำพิเศษ",
    tagType: "hot",
    image: "assets/images/product-15.jpg",
    imageCdn: "assets/images/product-15.jpg",
    description: "เดรสผ้าลูกไม้และผ้าคอตตอนเนื้อละเอียดพิเศษ ลายถักฉลุหวานหรูหรา ซับในคอตตอนนุ่ม 100% เหมาะสำหรับงานเฉลิมฉลอง ถ่ายภาพสตูดิโอ หรือของขวัญต้อนรับสมาชิกใหม่",
    sizes: ["3-6M", "6-12M", "1-2Y"],
    colors: [
      { name: "ขาวลูกไม้", code: "#ffffff" },
      { name: "ชมพูบลัช", code: "#ffb3c6" }
    ],
    inStock: true,
    features: ["ผ้าลูกไม้ถักประณีต", "ซับในคอตตอน 100%", "งานระดับงานเลี้ยงและสตูดิโอ"]
  },
  {
    id: 16,
    name: "ชุดว่ายน้ำเด็กกัน UV พร้อมหมวกคลุมกันแดด Little Wave",
    nameEn: "Baby UPF 50+ Sun Protection Swimsuit & Flap Hat Set",
    category: "swimwear",
    categoryName: "ชุดว่ายน้ำ",
    price: 490,
    originalPrice: 690,
    rating: 4.9,
    reviews: 128,
    tag: "กันแดด UPF50+",
    tagType: "hot",
    image: "assets/images/product-16.jpg",
    imageCdn: "assets/images/product-16.jpg",
    description: "ชุดว่ายน้ำเด็กเนื้อผ้าว่ายน้ำพรีเมียม ป้องกันรังสี UV สูงสุดระดับ UPF 50+ สกรีนลายสัตว์ทะเลพาสเทลสุดน่ารัก ซิปหน้าพร้อมแถบรองซิปกันหนีบผิว มาพร้อมหมวกว่ายน้ำปีกกว้างคลุมท้ายทอย ป้องกันแดดเผาผิวลูกน้อยได้อย่างมั่นใจ",
    sizes: ["6-12M", "1-2Y", "2-3Y", "3-4Y"],
    colors: [
      { name: "ชมพูหมึกทะเล", code: "#ffb3c6" },
      { name: "เหลืองพาสเทล", code: "#ffe066" }
    ],
    inStock: true,
    features: ["กันรังสี UV ระดับ UPF 50+", "แถมฟรีหมวกคลุมท้ายทอยกันแดด", "ซิปหน้าเซฟตี้การ์ด ไม่บาดผิว"]
  },
  {
    id: 17,
    name: "กางเกงผ้าอ้อมว่ายน้ำเด็กกันรั่วซึม ซักซ้ำได้ ลายไดโน & วาฬน้อย",
    nameEn: "Eco-Friendly Reusable Baby Swim Diaper Pants",
    category: "swimwear",
    categoryName: "ชุดว่ายน้ำ",
    price: 320,
    originalPrice: 450,
    rating: 5.0,
    reviews: 96,
    tag: "ไอเทมจำเป็น",
    tagType: "popular",
    image: "assets/images/product-17.jpg",
    imageCdn: "assets/images/product-17.jpg",
    description: "กางเกงผ้าอ้อมว่ายน้ำสำหรับเด็กอ่อนและเด็กเล็ก ป้องกันของเสียหรืออุจจาระเล็ดลอดลงสระน้ำตามมาตรฐานสระว่ายน้ำสากล เนื้อผ้านุ่มยืดหยุ่น ขอบเอวและขอบขากระชับพอดี ไม่อุ้มน้ำจนหนักตัว ซักทำความสะอาดง่ายและนำกลับมาใช้ซ้ำได้",
    sizes: ["0-6M", "6-12M", "1-2Y", "2-3Y"],
    colors: [
      { name: "เขียวมิ้นต์ไดโน", code: "#a0e8af" },
      { name: "ชมพูวาฬน้อย", code: "#ffb3c6" }
    ],
    inStock: true,
    features: ["กันของเสียรั่วซึม 100%", "ซักใช้ซ้ำได้ ประหยัดและรักษ์โลก", "ขอบยางนุ่มพิเศษ ไม่เป็นรอยแดง"]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCTS };
}
